JWT Auth
se2-group-h/the-note-storer pull request #9
Opened 2021-03-21 08:40 UTC by rshevchuk-git

All the init setup as well as the JWT functionality.

2021-03-21 16:24 UTC, kirylvolkau commented on backend/logs/spring-2020-12-20.log
> +2020-12-20 20:25:16 [INFO ] [restartedMain] sPropertyDefaultsPostProcessor: Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
Please, add .gitignore file to the backend directory with the following line: `**/*.log*`, stage it, commit and push. to this branch. I will see it.

2021-03-21 16:25 UTC, kirylvolkau commented on backend/logs/spring-2020-12-20.log
> +2020-12-20 20:25:16 [INFO ] [restartedMain] sPropertyDefaultsPostProcessor: Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
As the result, you will not have any logs in your folder. However, due to the nature of git, you may need to delete them manually.

2021-03-21 16:35 UTC, kirylvolkau requested changes
Cool, just please add `.gitignore` to the backend folder. You can use the following resource: 

https://www.toptal.com/developers/gitignore

Here you can enter multiple types of stuff to ignore in the form of tags. 
Also left some comments.

2021-03-21 16:35 UTC, kirylvolkau commented on backend/src/main/java/com/notes/backend/services/AuthService.java
> +        }
what is going on here XD

2021-03-21 16:35 UTC, kirylvolkau commented on backend/src/main/resources/application-dev.properties
> +# MySQL Database connection
XD

2021-03-21 16:35 UTC, kirylvolkau commented on backend/src/test/java/com/notes/backend/BackendApplicationTests.java
> +//}
Why is it commented?

2021-03-21 18:32 UTC, rshevchuk-git commented on backend/src/main/java/com/notes/backend/services/AuthService.java
> +        }
You really wanna know?) It has to do with a weird Spring implementation of BadCredentialsException which is for some reason a Runtime Exception so it's not explicitly visible for the compiler. It makes confusion because I haven't yet implemented my own exceptions, so those two will be later replaced by more reasonable names and will make more sense. For know I just used the highest level of exceptions hierarchy to not spend to much time on it

2021-03-21 18:34 UTC, rshevchuk-git commented on backend/src/main/resources/application-dev.properties
> +# MySQL Database connection
Forgot to change

2021-03-21 18:36 UTC, rshevchuk-git commented on backend/src/test/java/com/notes/backend/BackendApplicationTests.java
> +//}
It doesn't do anything

2021-03-21 18:41 UTC, rshevchuk-git commented on backend/logs/spring-2020-12-20.log
> +2020-12-20 20:25:16 [INFO ] [restartedMain] sPropertyDefaultsPostProcessor: Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
Done

2021-03-22 20:13 UTC, kirylvolkau commented on backend/src/main/java/com/notes/backend/services/AuthService.java
> +        }
Wow, this was informative, thanks

2021-03-22 20:14 UTC, kirylvolkau approved these changes

2021-03-22 20:14 UTC, kirylvolkau approved these changes

2021-03-22 20:15 UTC, merged